### ISSUE TITLE
SVG Icon Library example in webc

### ISSUE THREAD

**Issue by hexagoncircle** [11ty/eleventy-plugin-bundle#12]
Based on my understanding of the README examples for [SVG Icon Library](https://github.com/11ty/eleventy-plugin-bundle#svg-icon-library) and [React Helmet-style <head> additions](https://github.com/11ty/eleventy-plugin-bundle#react-helmet-style-head-additions), it seems like we can pull some HTML from a page or partial and render them in another part of the layout. How might we accomplish this in `webc` files?

I tried something like this but it didn't work:

```html
<!-- page.webc -->
<h2>hello</h2>
<g webc:bucket="svg" id="icon-close"><path d="…" /></g>
```

```html
<!-- layout.webc -->
<html>
  <head></head>
  <body>
    <svg width="0" height="0" aria-hidden="true" style="position: absolute">
      <defs @raw="getBundle('html', 'svg')"></defs>
    </svg>
    <div @raw="content"></div>
  </body>
</html>
```

**Comment by zachleat** [comment]
https://github.com/11ty/demo-webc-shadow-dom/blob/01a5d8c7db6df2874e28f4e050294c8607e139ba/_components/sample-component-sd.webc#L3-L11 might be the thing you’re looking for!

**Comment by zachleat** [comment]
https://github.com/11ty/demo-webc-shadow-dom/blob/01a5d8c7db6df2874e28f4e050294c8607e139ba/index.webc#L40 is the other piece to output the bundle.

**Comment by hexagoncircle** [comment]
That's exactly the thing I'm looking for! 🎉 This works for me:

```html
<!-- page.webc -->
<script webc:type="js" webc:nokeep>
  webc.helpers.html(
    `<g id="icon-close"><path d="…" /></g>`,
    "svg",
    $data.page.url
  );
</script>

<!-- referenced in a couple different places on the page -->
<svg><use xlink:href="#icon-close"></use></svg>
<svg><use xlink:href="#icon-close"></use></svg>
<svg><use xlink:href="#icon-close"></use></svg>
```

```html
<!-- layout.webc -->
<html>
  <head></head>
  <body>
    <svg width="0" height="0" aria-hidden="true" style="position: absolute">
      <defs @raw="getBundle('html', 'svg')"></defs>
    </svg>
    <div @raw="content"></div>
  </body>
</html>
```
