### ISSUE TITLE
Bundle Sass file?

### ISSUE THREAD

**Issue by bronze** [11ty/eleventy-plugin-bundle#13]
Hi.
I was reading up on the bundle and I dont know if this is possible.
instead of writing the scss directly, just import a scss file into the bundle.
Something like: `{%- css %}{% renderFile "src/css/tailwind.scss" template=scss %}{% endcss %}`

**Comment by nhoizey** [comment]
@bronze you can indeed do this by mixing these:
- https://github.com/11ty/eleventy-plugin-bundle#bundle-sass-with-the-render-plugin
- https://www.11ty.dev/docs/plugins/render/#renderfile
- https://www.11ty.dev/docs/languages/custom/#example-add-sass-support-to-eleventy
