### ISSUE TITLE
Option to use HTML `<style>` and `<script>` tags as delimiters instead of shortcodes

### ISSUE THREAD

**Issue by patrulea** [11ty/eleventy-plugin-bundle#15]
It would be useful to write styles and scripts within regular HTML tags instead of shortcodes to get the most of validation, IntelliSense and other features in code editors.

Currently, I’m wrapping `<style>` around `{% css %}` but this leaves the output with empty `<style>` elements scattered across the DOM.

**Desired syntax**

```html
<style data-bundle="bucket_name">
  strong {
    font-weight: bold;
  }
</style>
```

**Comment by zachleat** [comment]
just for the record, WebC does this https://github.com/11ty/webc

**Comment by patrulea** [comment]
Great! I’ll have to check WebC out.

But can this behavior be replicated for good old Liquid and Nunjucks?

**Comment by TristanPct** [comment]
One workaround is to wrap in the other way:

```html
{% css %}
<style>
    ::placeholder {
        color: red;
    }
</style>
{% endcss %} 
```

And inside your bundler transforms you can remove these tags:

```js
      transforms: [
          function (content) {
              if (this.type === "css") {
                  return content.replace(/^<style>/, "").replace(/<\/style>$/, "");
              }
              
              if (this.type === "js") {
                  return content.replace(/^<script>/, "").replace(/<\/script>$/, "");
              }

              return content;
          }
      ]
```

**Comment by patrulea** [comment]
Thank you Tristan! I was looking for a way to do exactly that.
