### ISSUE TITLE
{% javascript %} and {% stylesheet %}

### ISSUE THREAD

**Issue by chee** [11ty/eleventy-plugin-bundle#22]
i've made the issue title generic because i don't want to XY Problem or come up with a predefined solution in the issue when the issue could have multiple solutions, feel free to change the title when that's more clear.

basically i'm using eleventy-plugin-bundle with a `bundles:` config of `["stylesheet", "javascript"]` but when i use `getBundleFileUrl` the url extension is `.stylesheet` and `.javascript`. i'd love if these were `.css` and `.js`

the reason i'm using "stylesheet" and "javascript" is that [my text editor's syntax highlighting](https://web-mode.org/) highlights css and js inside `{% stylesheet %}{% endstylesheet %}`/`{% javascript %}{% endjavascript %}` tags, and [shopify's prettier liquid plugin](https://shopify.dev/docs/themes/tools/liquid-prettier-plugin) doesn't squanch up the content of those tags and actually formats them correctly using its css/js parser/formatter.

is there a way to change the extension of the bundle file url? or: is there a way of aliasing a bundle under another name? or: is there another thing you can think of other than me forking web-mode and the shopify plugin to make `eleventy-mode` and `prettier-plugin-eleventy`? hehe

thx! wonderful project, btw, having a great time

**Comment by zachleat** [comment]
Shipped with v2.0.0 via the `outputFileExtension` option: https://github.com/11ty/eleventy-plugin-bundle?tab=readme-ov-file#full-options-list

Stay tuned, the bundled version of this plugin is coming to Eleventy core v3.0.0-alpha.10.

**Comment by chee** [comment]
fab!!!! thank you so much, this is exciting
