### ISSUE TITLE
Conditional <script> tags

### ISSUE THREAD

**Issue by adamwolf** [11ty/eleventy-plugin-bundle#8]
I'm loving this plugin!

I was working on a little site where some pages had some non-essential Javascript that I put at the end of the body.  I set up a noncritical bundle, and it worked pretty well, until I tried to make the whole script tag conditional on the noncritical bundle being empty.

At first, I was pretty confused because nunjucks was saying that the contents of the bundle were both the empty string and also 40-some characters long, but of course this ended up being the out-of-order render stuff.  I tried to dig in a bit more and get the conditional tags, but I didn't understand the out-of-order render stuff enough to get it to work.

I ended up adding a "hasNoncriticalJS" boolean on the whole page and including the `<script>` tag and contents based on that boolean.

It works fine--but now I'm really curious. :)

Is this already supported?  If it isn't, is there anywhere where it'd make sense to add something like this?  A way to put a prefix-suffix around a bundle if the bundle isn't empty, maybe?

**Comment by zachleat** [comment]
It isn’t supported yet! I would like to have this though!

I’ve been thinking on it—I’m curious how to maintain full control over the parent HTML without it being too esoteric (a la the prefix/suffix idea)

**Comment by adamwolf** [comment]
The syntax might be the hardest part! :)

**Comment by essarefess** [comment]
> At first, I was pretty confused because nunjucks was saying that the contents of the bundle were both the empty string and also 40-some characters long, but of course this ended up being the out-of-order render stuff.

Ran into this myself today, trying skip empty `<script>`s, the multi-character empty string was a head-scratcher 😅

It finally clicked that the `/*__EleventyBundle:${type}:${name}:${bucket || "default"}:EleventyBundle__*/` returned to the shortcodes by `OutOfOrderRender.getAssetKey()` is getting replaced with the actual bundle content (the empty string) at a later point, but that's what Nunjucks is seeing at the point it's doing its own processing.

For now, this is working in Nunjucks to exclude the empty `<script>`s for the default css bucket:

```njk
{%- set pageCSS %}{% getBundle "css" %}{% endset %}
{%- if not pageCSS == "/*__EleventyBundle:get:css:default:EleventyBundle__*/" %}
<style>{{ pageCSS }}</style>
{%- endif %}
```

Looking forward to potential official support, but this workaround should do the trick for now. (I haven't dipped my toe into WebC yet, but maybe this could be used in the WebC if conditionals as well @noelforte)

**Comment by noelforte** [comment]
A workaround that just came to me today that I've implemented and it works great is to add an HTML transform that looks for empty `<style>`, `<script>` and `<link>` tags resulting from empty bundles and does a string replace to eliminate them from the output. Not a perfect solution but it gets the job done. Details are here: https://github.com/11ty/eleventy-plugin-webc/issues/82#issuecomment-1912897259

**Comment by zachleat** [comment]
Shipping with Bundle Plugin v3.0.0 as part of Core v3.0.0-alpha.21 and v3.0.0-beta.2
